language: generic
  
deploy:
  - provider: script
    skip_cleanup: true
    script: "./deploy.sh"
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY_ID
    secret_access_key: $AWS_SECRET_ACCESS_KEY
    bucket: terraform.aliciasteen.com
    skip_cleanup: true
    local_dir: site
    region: eu-west-1
